@startuml
title StackExchange UseCases

left to right direction

actor "Anonymous" as NAU
actor "Authorized user" as AU
actor "Guest user" as GU

actor Asker as ASK_U
actor Answerer as ANS_U
actor Searcher as SEA_U
actor Moderator as MOD_U

ASK_U -u-|> AU
ANS_U -u-|> AU
ANS_U -l-|> GU
SEA_U -u-|> NAU
SEA_U -u-|> AU
MOD_U -u-|> AU

' text
usecase "Create publication" as UCpub
usecase "Use markup" as UCq_markup
usecase "Attach media" as UCq_media

UCpub <.. UCq_markup : <<extend>>
UCpub <.. UCq_media : <<extend>>


' create
usecase "Assign tags" as UCq_tag
usecase "Create Question" as UCcreate

ASK_U --> UCcreate
UCcreate ..> UCq_tag : <<include>>
UCcreate ..> UCpub : <<include>>


' answer
usecase "Answer Questions" as UCanswer

ANS_U --> UCanswer
UCanswer ..> UCpub : <<include>>


' vote
usecase "Vote on Questions and Answers" as UCvote
usecase "Rank Answers" as UCrank
usecase "Accept Answers" as UCaccept

AU --> UCvote
ASK_U --> UCrank
UCrank ..> UCaccept : <<include>>
UCrank ..> UCvote : <<include>>

' answers
usecase "Search questions" as UCsearch
usecase "Filter questions" as UCq_filter
usecase "Sort questions" as UCq_sort
usecase "List answers" as UCa_list
usecase "Sort answers by ranking" as UCa_sort

SEA_U --> UCsearch

UCsearch <.. UCq_filter : <<extend>>
UCsearch <.. UCq_sort : <<extend>>

UCsearch ..> UCa_list : <<include>>
UCa_list <.l. UCa_sort : <<extend>>

' comments
usecase "Comment on Questions and Answers" as UCcomment
usecase "View comments" as UCcomment_view
usecase "Rank comments" as UCcomment_rank

AU ---> UCcomment
UCa_list <.. UCcomment_view : <<extend>>
UCcomment_view .r.> UCcomment_rank : <<include>>

' moderate
usecase "Moderate Questions and Answers" as UCmod
usecase "Edit text" as UCmod_edit
usecase "Ban posts" as UCmod_ban

MOD_U --> UCmod
UCmod <.. UCmod_edit  : <<extend>>
UCmod <.. UCmod_ban  : <<extend>>


@enduml